# Generated by Django 4.0.3 on 2022-03-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ism',
        ),
    ]
